name: Check Changes in Compose Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # You can change this to your preferred distribution

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Detect changes in Compose
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        echo "Changed files: $CHANGED_FILES"
        if echo "$CHANGED_FILES" | grep -qE '^app/src/main/java/com/example/audio_kotlin/.*'; then
          echo "Changes detected in Compose application"
        else
          echo "No changes detected in Compose application"
        fi

    - name: Notify if changes detected
      if: ${{ steps.detect_changes.outputs.changes_detected == 'true' }}
      run: echo "Notify team about changes in Compose application"
